### ISSUE TITLE
`auto-palette` does not compile with Rust stable (1.86.0)

### ISSUE THREAD

**Issue by gferon** [t28hub/auto-palette#184]
**Describe the bug**

I tried to upgrade `auto-palette` in my tree and got:

```rust
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/gabe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/auto-palette-0.8.0/src/lib.rs:1:1
  |
1 | #![feature(array_chunks, coverage_attribute)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**

1. Try to build `auto-palette` with Rust 1.86.0
2. Observe build failure

**Expected behavior**

I believe this crate should strive to build on Rust stable versions.

**Additional context**

If you really want to keep those features without additional tricks, you _could_ add a dependency to [`rustversion`](https://crates.io/crates/rustversion) and gate your feature flags. Otherwise, you could use plain feature flags that you toggle in CI, but you might want to add a workflow in CI that tries to build the crate on Rust stable.
